AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template

Parameters:
  FrontendRepository:
    Type: String
    Description: "The repository URL for the frontend application."

  GitHubTokenSecretName:
    Type: String
    Description: "The name of the secrets storing GitHub token for accessing the repository."

Resources:
  AmplifyFrontendApp:
    Type: "AWS::Amplify::App"
    Properties:
      Name: !Sub "${AWS::StackName}-${AWS::Region}-${AWS::AccountId}"
      Repository: !Ref FrontendRepository
      BuildSpec: |
        version: 1
        applications:
          - frontend:
              phases:
                preBuild:
                  commands:
                    - npm ci
                build:
                  commands:
                    - npm run build
              artifacts:
                baseDirectory: dist
                files:
                  - '**/*'
              cache:
                paths:
                  - node_modules/**/*
              appRoot: frontend
      AccessToken: "{{resolve:secretsmanager:${GitHubTokenSecretName}}}"
      EnvironmentVariables:
        - Name: "AMPLIFY_MONOREPO_APP_ROOT"
          Value: "frontend"
        - Name: "VITE_REGION"
          Value: !Ref "AWS::Region"
        - Name: "VITE_API_ENDPOINT"
          Value: "{{resolve:ssm:APIGWInvokeEndpoint}}"
        - Name: "VITE_USER_POOL_ID"
          Value: "{{resolve:ssm:UserPoolID}}"
        - Name: "VITE_USER_POOL_CLIENT_ID"
          Value: "{{resolve:ssm:UserPoolClientID}}"

  AmplifyBranch:
    Type: "AWS::Amplify::Branch"
    Properties:
      BranchName: "main"
      AppId: !Ref AmplifyFrontendApp
      EnableAutoBuild: true

